# Generated by Django 2.0.2 on 2019-03-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('interview', '0001_initial'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Interview', verbose_name='面试'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Position', verbose_name='职位'),
        ),
    ]
