# Generated by Django 2.0.2 on 2019-03-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        ('delivery', '0002_auto_20190308_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume', verbose_name='简历'),
        ),
    ]
