# Generated by Django 2.0.2 on 2019-02-26 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnterPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='企业ID')),
                ('name', models.CharField(max_length=50, verbose_name='企业名称')),
                ('product_desc', models.TextField(verbose_name='产品介绍')),
                ('enterprice_desc', models.TextField(verbose_name='产品介绍')),
                ('enterprice_gm', models.CharField(choices=[('JXQY', '10-49人'), ('XQY', '50-99人'), ('ZXQY', '100-499人'), ('ZQY', '500-1000人'), ('DQY', '1000-5000人'), ('JT', '5000人以上')], default='XQY', max_length=20)),
                ('enterprice_type', models.CharField(choices=[('MI', '移动互联网'), ('ET', '电信'), ('FT', '金融'), ('DS', '电商'), ('ZQ', '证券'), ('WLW', '物联网')], default='MI', max_length=20, verbose_name='所属行业')),
                ('finance_stage', models.CharField(choices=[('WRZ', '未融资'), ('TSL', '天使轮'), ('AL', 'A轮'), ('BL', 'B轮'), ('CL', 'C轮'), ('BXY', '不需要融资')], default='BXY', max_length=10, verbose_name='融资阶段')),
                ('logo', models.ImageField(upload_to='enterprice/%Y/%m', verbose_name='logo')),
                ('address', models.CharField(max_length=150, verbose_name='企业地址')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='OfferID')),
                ('salary', models.CharField(max_length=32, verbose_name='薪资待遇')),
                ('offer_desc', models.TextField(verbose_name='offer描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('offer_status', models.CharField(choices=[('WX', '无效'), ('YX', '有效'), ('WJ', '婉拒'), ('AC', '接受')], default='WX', max_length=2, verbose_name='offer状态')),
                ('enterprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.EnterPrice', verbose_name='企业')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offer',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='职位ID')),
                ('name', models.CharField(max_length=64, verbose_name='职称')),
                ('city', models.CharField(max_length=64, verbose_name='工作城市')),
                ('position_type', models.CharField(choices=[('QZ', '全职'), ('JZ', '兼职')], max_length=2, verbose_name='职位类型')),
                ('experience_required', models.CharField(choices=[('YJ', '应届生'), ('XS', '1-3年'), ('ZJ', '3-5年'), ('GJ', '5-7年'), ('ZJ', '7年以上'), ('DK', '10年以上')], max_length=2, verbose_name='工作经验要求')),
                ('degree_required', models.CharField(choices=[('BK', '本科'), ('SS', '硕士'), ('BS', '博士'), ('DZ', '大专'), ('GZ', '高中'), ('MBA', 'MBA'), ('CZ', '初中')], max_length=3, verbose_name='最低学历要求')),
                ('attractive_desc', models.TextField(blank=True, null=True, verbose_name='职位诱惑')),
                ('position_desc', models.TextField(blank=True, null=True, verbose_name='职位描述')),
                ('position_status', models.CharField(choices=[('YX', '有效'), ('WX', '无效')], default='YX', max_length=2, verbose_name='职位状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('enterprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.EnterPrice', verbose_name='企业')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.Position', verbose_name='职位'),
        ),
    ]
