# Generated by Django 2.0.2 on 2019-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='简历ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('creer_time', models.IntegerField(default=0, verbose_name='工作年限')),
                ('gender', models.CharField(default='male', max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='城市')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱地址')),
                ('school', models.CharField(max_length=64, verbose_name='毕业院校')),
                ('degree', models.CharField(default='本科', max_length=10, verbose_name='最高学历')),
                ('major', models.CharField(max_length=64, verbose_name='专业')),
                ('self_desc', models.TextField(verbose_name='自我描述')),
                ('lastest_job_desc', models.TextField(verbose_name='最近一份工作描述')),
                ('lastest_job_position', models.TextField(verbose_name='最近一份工作职称')),
                ('desire_position', models.CharField(max_length=32, verbose_name='期望职位')),
                ('job_type', models.CharField(default='全职', max_length=2, verbose_name='工作性质')),
                ('desire_monthly_salary', models.CharField(blank=True, max_length=16, null=True, verbose_name='期望月薪')),
                ('desire_city', models.CharField(blank=True, max_length=32, null=True, verbose_name='期望城市')),
                ('current_status', models.CharField(default='已离职', max_length=4, verbose_name='当前状态')),
                ('is_public', models.IntegerField(default=0, verbose_name='是否开启邀约')),
                ('speciality', models.TextField(verbose_name='特长优势')),
            ],
            options={
                'verbose_name': '我的简历',
                'verbose_name_plural': '我的简历',
            },
        ),
    ]
