# Generated by Django 2.0.2 on 2019-03-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('enterprice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='面试ID')),
                ('interview_arrangement', models.TextField(verbose_name='面试安排')),
                ('interview_status', models.CharField(choices=[('YM', '已面试'), ('JM', '将面试'), ('LY', '录用'), ('WLY', '未录用')], default='JM', max_length=2, verbose_name='面试状态')),
                ('enterprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprice.EnterPrice', verbose_name='企业')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Position', verbose_name='职位')),
            ],
            options={
                'verbose_name': '面试',
                'verbose_name_plural': '面试',
            },
        ),
    ]
