# Generated by Django 2.0.2 on 2019-03-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remove_delivery_interview'),
        ('interview', '0002_interview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.Delivery', verbose_name='投递'),
            preserve_default=False,
        ),
    ]
