# Generated by Django 2.0.2 on 2019-03-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('collection', '0001_initial'),
        ('enterprice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='enterprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprice.EnterPrice', verbose_name='企业'),
        ),
        migrations.AddField(
            model_name='collection',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Position', verbose_name='职位'),
        ),
    ]
