# Generated by Django 2.0.2 on 2019-02-26 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='收藏ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('collection_status', models.CharField(choices=[('WX', '无效'), ('YX', '有效')], max_length=2, verbose_name='收藏状态')),
                ('enterprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.EnterPrice', verbose_name='企业')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.Position', verbose_name='职位')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='投递ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='投递时间')),
                ('delivery_status', models.CharField(choices=[('YQ', '邀请面试'), ('WJ', '婉拒')], max_length=2, verbose_name='投递状态')),
                ('enterprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.EnterPrice', verbose_name='企业')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.Position', verbose_name='职位')),
            ],
            options={
                'verbose_name': '面试',
                'verbose_name_plural': '面试',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='面试ID')),
                ('interview_arrangement', models.TextField(verbose_name='面试安排')),
                ('interview_status', models.CharField(choices=[('YM', '已面试'), ('JM', '将面试'), ('LY', '录用'), ('WLY', '未录用')], default='JM', max_length=2, verbose_name='面试状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('enterprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.EnterPrice', verbose_name='企业')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiters.Position', verbose_name='职位')),
            ],
            options={
                'verbose_name': '面试',
                'verbose_name_plural': '面试',
            },
        ),
        migrations.CreateModel(
            name='Resumer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='简历ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('creer_time', models.IntegerField(default=0, verbose_name='工作年限')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='城市')),
                ('mobile', models.CharField(max_length=20, verbose_name='手机')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱地址')),
                ('school', models.CharField(max_length=64, verbose_name='毕业院校')),
                ('graduate_time', models.DateField(max_length=10, verbose_name='毕业时间')),
                ('degree', models.CharField(choices=[('BK', '本科'), ('SS', '硕士'), ('BS', '博士'), ('DZ', '大专'), ('GZ', '高中'), ('MBA', 'MBA'), ('CZ', '初中')], default='BK', max_length=10, verbose_name='最高学历')),
                ('major', models.CharField(max_length=64, verbose_name='专业')),
                ('self_desc', models.TextField(verbose_name='自我描述')),
                ('lastest_job_desc', models.TextField(verbose_name='最近一份工作描述')),
                ('lastest_job_position', models.TextField(verbose_name='最近一份工作职称')),
                ('desire_position', models.CharField(max_length=32, verbose_name='期望职位')),
                ('job_type', models.CharField(choices=[('QZ', '全职'), ('JZ', '兼职')], default='QZ', max_length=2, verbose_name='工作性质')),
                ('desire_monthly_salary', models.CharField(blank=True, max_length=16, null=True, verbose_name='期望月薪')),
                ('desire_city', models.CharField(blank=True, max_length=32, null=True, verbose_name='期望城市')),
                ('current_status', models.CharField(default='LZ', max_length=4, verbose_name='当前状态')),
                ('speciality', models.TextField(verbose_name='特长优势')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '我的简历',
                'verbose_name_plural': '我的简历',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('name', models.CharField(choices=[('user', '求职者'), ('recruiter', '招聘人')], max_length=10, verbose_name='角色名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nick_name', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=10, verbose_name='性别')),
                ('email', models.EmailField(default='', max_length=64, verbose_name='电邮地址')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y%m')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applyers.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.AddField(
            model_name='resumer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applyers.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applyers.User', verbose_name='用户'),
        ),
    ]
