# Generated by Django 2.0.2 on 2019-02-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applyers', '0002_auto_20190226_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applyers.Role', verbose_name='角色'),
        ),
    ]
