# Generated by Django 2.0.2 on 2019-02-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyers', '0003_auto_20190226_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumer',
            name='graduate_time',
        ),
    ]
