# Generated by Django 2.0.2 on 2019-02-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyers', '0004_remove_resumer_graduate_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumer',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AddField(
            model_name='resumer',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
    ]
