# Generated by Django 2.0.2 on 2019-03-08 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('enterprice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='OfferID')),
                ('salary', models.CharField(max_length=32, verbose_name='薪资待遇')),
                ('offer_desc', models.TextField(verbose_name='offer描述')),
                ('offer_status', models.CharField(choices=[('WX', '无效'), ('YX', '有效'), ('WJ', '婉拒'), ('AC', '接受')], default='WX', max_length=2, verbose_name='offer状态')),
                ('enterprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprice.EnterPrice', verbose_name='企业')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Position', verbose_name='职位')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offer',
            },
        ),
    ]
